# Generated by Django 5.2.1 on 2025-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=' ', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
